# -*- coding: utf-8 -*-
GAP = "[gap in notes]"
PROSE = {
"ahmednagar": f"""The seat of the {GAP} Sultanate, founded by Malik Ahmad, Bahmani governor of Junnar, in 1490. It lasted until 1636, when it was conquered by Shah Jahan. Aurangzeb died here in 1707.""",
"ajmer-sharif": """The resting place of Muinuddin Chishti. Akbar and many later Mughals continued to visit the dargah.""",
"atiya-jame-masjid": """A medieval mosque in Bangladesh built of brick in 1609, notable for its Bangla roof.""",
"fatehpur-sikri": """The site of the tomb of Salim Chishti.""",
"gaur-or-lakhnauti": """A city which gained prominence under the Sena dynasty and was later controlled by the governors Iltutmish and Muhammad bin Bakhtiyar. It came under the Sultanate of Bengal and was sacked by Sher Shah.""",
"ghazni": """The capital of the Ghaznavids. The pre-Islamic city was largely tribal and practised Buddhism and Hinduism. Islamic conquest began in the seventh century and resumed in the ninth. It fell to the British in 1839.""",
"golconda": """The capital of the medieval sultanate of the Qutb Shahi dynasty, about 1518 to 1687.""",
"gulbarga": """A city in Karnataka, now known as Kalaburagi, in existence since the sixth century in Rashtrakuta times. It fell to the Delhi Sultanate after the defeat of the Kakatiyas in 1321. The tomb of the Sufi saint Syed Shah Qhabulullah is located here.""",
"lahore": """A city whose early occupants included Mahmud of Ghazni, for whom it served as a second capital. It later became Akbar's capital; Jahangir's tomb stands here, and Aurangzeb extended the Lahore Fort.""",
"multan": """A principal trade centre during the Delhi Sultanate, in Pakistan. The shrine of Bahauddin Zakariya is located here.""",
"ramadevra": """A site in Rajasthan named after a fourteenth-century ruler said to have possessed miraculous powers, who worked for the upliftment of the poor and downtrodden and is now venerated as a local deity.""",
"sasaram": """The place where Sher Shah Suri was born and buried. His tomb, of red sandstone in the Indo-Afghan style, is famous.""",
"shah-hamdam": """A medieval building on the banks of the Jhelum, built in 1395, and one of the best examples of Kashmiri wooden architecture, decorated with papier mâché.""",
"tatha": """The site of the Makli Necropolis, one of the world's largest cemeteries, with many tombs built between the fourteenth and eighteenth centuries.""",
"uch": f"""A stronghold under the Delhi Sultanate and a Suhrawardi Sufi centre, its saint a follower of Bahauddin Zakariya. Qubacha was governor of {GAP}. Guru Nanak visited the shrine and left five relics here.""",
"vijayapura-or-bijapur": """A medieval city founded by Yusuf Adil Shah. The Gol Gumbaz here, the tomb of Adil Shah, has the largest dome in India.""",
"akhnoor": """A fort on the right bank of the Chenab in Jammu and Kashmir, begun by Mian Tej Singh in 1762 AD and completed by Raja Alum Singh in 1802.""",
"amber": f"""A fort in Rajasthan built by Raja Man Singh of {GAP} over an earlier structure raised by Raja Alan Singh. The main entry is through the Suraj Pol, or Sun Gate, leading to the main courtyard.""",
"bekal": """The largest fort in Kerala, constructed in 1650 AD by Shivappa Nayaka of Keladi, successors of the Nayakas of the Vijayanagara empire.""",
"chitorgarh": """The largest fort in India and a UNESCO World Heritage Site, and capital of Mewar. Alauddin Khalji defeated Ratan Singh here in 1303, and Akbar defeated Maharana Udai Singh in 1567.""",
"cooch-behar": """A palace also called the Victor Jubilee Palace, designed on the model of Buckingham Palace with Corinthian columns, built in 1887 during the reign of Maharaja Nripendra Narayan.""",
"gagron-fort": """One of the six hill forts of Rajasthan, with occupants ranging from the Doda Rajputs to Akbar. The mausoleum of the Sufi saint Mitthe Shah, outside the fort, is the venue for a fair during Muharram.""",
"garhgaon": """The capital of the Ahom kingdom, its fort built by the Ahom king Suklenmung in 1540.""",
"gingee": f"""A fort in Villupuram district, originally built by the Konar dynasty and later by the Chola and Vijayanagara empires. It served as headquarters of the {GAP} Nayakas. Its occupants included Shivaji, the Sultan of Bijapur, the French and the British. It is associated with Raja Tej Singh, who revolted against the Nawab of Arcot.""",
"gwalior": """A fort in Madhya Pradesh in its present form built by Man Singh Tomar in the fifteenth century. A sun temple predating the fort was built by the Huna emperor Mihirakula, and Jaina rock-cut caves and monuments stand nearby.""",
"hawa-mahal": """A building in Rajasthan built by Sawai Pratap Singh in 1799, in Rajput architecture, with elaborate jharokhas and latticework.""",
"jaisalmer-fort-palace": """A fort built by Rawal Jaisal in 1156 and an important silk route site. It was besieged by Alauddin Khalji.""",
"kangla": """A fort on the banks of the Imphal river in Manipur, attacked during the first Anglo-Manipur war in 1891.""",
"kumbhalgarh": """A World Heritage Site built in the fifteenth century by Rana Kumbha of the Mewar Rajputs, separating Mewar from Marwar. It was the birthplace of Maharana Pratap.""",
"mandu": """A fortified town in Dhar district since ancient times, which gained prominence under the Paramaras, rulers of Malwa, who named it Mandavgarh. The present structures were built under Hoshang Shah of Malwa; the walls slope at seventy-seven degrees to give the effect of swaying.""",
"mehrangarh": """A fort in Rajasthan built in 1459 by Rao Jodha. Its foundation was laid by Karni Mata, a saint worshipped as a local deity.""",
"raigad": """A fort built by Chandrarao More and soon afterwards captured by Shivaji Maharaj, who renamed it.""",
"ranthambore": """A fort whose foundation was laid by Sapaldaksha of the Chauhan Rajputs. It was a bastion of Prithviraj III of the Chauhans and later held under Mewar kings such as Rana Sanga.""",
"srirangapatnam": """A fort built in 1454 by Timmanna Nayaka of the Vijayanagara empire with French assistance. Tipu Sultan was killed here.""",
"warangal": """The capital of the Kakatiya dynasty, in Telangana, built by Ganapatideva in the thirteenth century. It was besieged by Malik Kafur in 1309 against Prataparudra II.""",
"apegaon-janeshwar": """Associated with Dnyaneshwar, a thirteenth-century Marathi saint under the Yadava dynasty. He wrote the Dnyaneshwari and the Amrutanubhav in Marathi, and his philosophy was the non-dualist Advaita Vedanta.""",
"bagewadi-basava": """Associated with Basava, a Shaivite saint of the Sharana sect who flourished during the reign of Bijjala II of the Chalukya-Kalachuri dynasty in the twelfth century. He wrote Vachana Sahitya in Kannada, gave people the ishtalinga, a necklace, and introduced new public institutions such as the Anubhava Mandapa.""",
"bannur-vyastirtha": """Associated with Vyasatirtha, a fifteenth-century saint of the Dvaita Vedanta from Karnataka, and patron saint of the Vijayanagara empire under Krishnadevaraya. Among his works are the Nyayamrita and the Tarkatandava.""",
"champaran-vallabhacharya": """Associated with Vallabhacharya, who founded the Pushti sect of Vaishnavism in the Braj region and the philosophy of Shuddhadvaita, or pure non-dualism.""",
"dehu-tukaram": """Associated with Tukaram, a Bhakti saint of Maharashtra whose poetry is known as abhanga and whose spiritual songs are kirtans, both devoted to Vitthala. The abhanga is a simple, direct poetic form fused with folk stories and spiritual in theme. He was a disciple of Babaji Chaitanya.""",
"jalna-ramdas": """Associated with Ramdas, a seventeenth-century devotee of Rama and Hanuman and patron saint of Shivaji, whom he is said to have blessed to be a champion of Hinduism. His famous work is the Dasbodh.""",
"kaladi-adi-shakaracharya": """Associated with Adi Shankaracharya, who consolidated the Advaita Vedanta philosophy. His works concentrate on the atman and nirguna brahman, and he organised the Dashanami monastic order.""",
"karaikal-ammaiyar": """Associated with Karaikal Ammaiyar, a sixth-century Shiva worshipper of the Chola period and one of only three such saints. Born to a merchant family as Punithavathi, she married a wealthy merchant, and is associated with the mango story. Her two works are the Tiruvantadi and the Tiru-irattai.""",
"kurki-mirabai": """Associated with Mirabai, a sixteenth-century Bhakti saint of Rajasthan and devotee of Krishna, whom she treated as her husband. Married to Bhoj Raj, prince of Mewar, she was persecuted by her in-laws. Her hymns are known as bhajans.""",
"lal-ded-pandrethan": """Associated with Lal Ded, a fourteenth-century Shaivite mystic and creator of the poetry known as vatsun, vakh or Lal Vakh, among the earliest compositions in the Kashmiri language.""",
"melur-mannikavasagar": """Associated with Manikkavasagar, a ninth-century poet who lived in Madurai and wrote the Tiruvasakam, a key text of Shaiva Siddhanta, and also the Tirumurai.""",
"nagaon-shankardev": """Associated with Shankardev, a fifteenth-century Bhakti saint of Assam who began the neo-Vaishnavite movement. The Sattriya dance, Borgeet songs and Ankiya Naat drama are attributed to him.""",
"naraina-dadu": """Associated with Dadu, founder of the Dadupanth, who preached near Jaipur and held that devotion to God should be beyond sectarian belief. His disciple Rajjab composed his verses as the Dadu Anubhav Vani.""",
"paithan-eknath": """The capital of the Satavahanas, from about 200 BC to 200 AD, important for trade and commerce, and mentioned by Ptolemy and in the Ashokan rock edicts. It is associated with Eknath, a devotee of Krishna and poet of the Varkari tradition, who wrote the Eknathi Bhagavata, a commentary on the Bhagavata Purana, and formed the bridge between his predecessors Dnyaneshwar and Namdev.""",
"runkata-surdas": """Associated with Surdas, a blind saint inspired by Vallabhacharya, who wrote in the Braj dialect. He composed the Sur Sagar, describing the love between Krishna and Radha, together with the Sur Saravali and the Sahitya Lahari. Some of his works appear in the Guru Granth Sahib.""",
"sriperumbudur-ramanuja": """Associated with Ramanuja, proponent of the Vishishtadvaita school of Vedanta, who studied at Kanchi as a disciple of Yadava Prakasa. He wrote commentaries in Sanskrit on the Brahma Sutra and the Bhagavad Gita.""",
"srivilliputur-andal": """Associated with Andal, the only female saint among the twelve Alvars of south India and a follower of the Srivaishnava tradition. Her works include the Thiruppavai and the Nachiar Tirumozhi.""",
"talaja-narsinh-mehta": """Associated with Narsinh Mehta, revered as the Adi Kavi of Gujarati literature, who wrote the poem Vaishnava Jana To.""",
"tirthahalli-purandarasa": """Associated with Purandara Dasa, a fifteenth-century saint, poet, devotee of Krishna and social reformer under the Vijayanagara empire, and a disciple of Vyasatirtha. He is said to have composed the basics of Carnatic music, structuring it into svaravalis and alankaras, and also composed gitas, or simple songs, and Dasa Sahitya.""",
"varanasi-ramananda-kabir-rai-ravidas": """A city in Uttar Pradesh which the Jataka stories describe as one of the most powerful of the mahajanapadas, famed for fine textiles and an important trade centre. It was surrounded by a rampart, and remains of a burnt clay floor and terracotta rings survive. It came into conflict with Kosala, Anga and Magadha. It was an educational centre for Hindus, Buddhists and Jainas alike, where the Vedas and Upanishads were taught. The twelfth jyotirlinga is at the Kashi Vishwanath temple, and the Banaras gharana of Hindustani classical music developed here.""",
}
